name: Linux CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Build
        run: zig build

      - name: Run
        run: zig build run

      - name: Test
        run: zig build test

